### ISSUE TITLE
Https: Error Connection

### ISSUE THREAD

**Issue by wpoptimer** [evertramos/docker-wordpress#49]
Hi,

I'm getting this error while accessing the site from https .

i think the reverse proxy is not working.

i have followed all the instructions .

Can you tell me what can be the problem.

Thank you  :)

**Comment by evertramos** [comment]
is the proxy working? did you tested it first? what are the logs? the errors? ... need some info.... follow the proxy readme carefully and then this repo it shoudl work smothly. what linux version you are using it? what host provider?
