### ISSUE TITLE
Usage of REPLACE_ environmental variables.

### ISSUE THREAD

**Issue by ardiewen** [evertramos/docker-wordpress#51]
Hi there, first of all thanks for setting up this repo. It's helped tremendously for setting up my development environments.

I'm adapting this for my own use case where for each project, I spin up 3 wordpress instances (e.g. prod, staging, dev) while maintaining a single shared database container.

So far so good, but I cannot seem to find any usage / reference to the `REPLACE_DB_SERVICE_NAME` and `REPLACE_SITE_SERVICE_NAME` environmental variables found at the bottom of the .env.sample file:

```
# docker-compose service name
#
# This variables below are used for the automation process
# and must be the same name used in docker-composer.yml
REPLACE_DB_SERVICE_NAME=new-site-db
REPLACE_SITE_SERVICE_NAME=new-site-wordpress
```

I've looked in both this repo and the [webproxy parent repo](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) and can't seem to find any references to it.

Can you confirm whether or not this is still required as part of the usage?

**Comment by evertramos** [comment]
Hello @ardiewen

Nicely well noted! Yes this is a personal requirement for a larger script I have and still haven't finished yet... but I am using in production for the last 5 years now. So this is a requirement. 

I am planning to open source it soon.

The script does some of the following:

- fire new site
- clone site
- backup
- restore
- restore to new url
- set domain dns 
- install wp plugins
- .... etc

**Comment by ardiewen** [comment]
@evertramos thanks for confirming, cheers!
