### ISSUE TITLE
wp-config.php missing configuration

### ISSUE THREAD

**Issue by damon-t** [evertramos/docker-wordpress#54]
Hi,

after running a fresh container the wp-config.php file is not set with the right data from the .env file. with the previous version it was working.
Could you please take a look on this?

**Comment by evertramos** [comment]
what is missing?

**Comment by damon-t** [comment]
I just ran into an error while running wpcli.

actually I thought that the MySQL settings in wpconfig.php will be get from the .env file. So I don't need to paste the same data again in a different file, or do I have to? 
Sorry, If it's confusing, do you know what I mean?

**Comment by evertramos** [comment]
no I don't... you must use wp cli as of:

```bash
docker-compose run --rm wpcli
```

please check:
```bash
./wp-cli-test.sh
```

**Comment by damon-t** [comment]
sure, I am running wp-cli like you mentioned. 
Do I have to configure wp-config.php manually before I can run wp-cli?
