### ISSUE TITLE
wordpress 6.0.2 and mysql 8.0

### ISSUE THREAD

**Issue by nnachtegael** [evertramos/docker-wordpress#61]
maybe a bug?
when I try to combine wordpress 6.0.2 and mysql 8.0 in the wordpress/.env file
./new-site.sh, was successful but the docker ps command tells the mysql db is restarting in a loop.

(I have also the  ✘ ERROR   You dont have permission to write log at '/var/log/basescript.log'  during scripts execution.)

Wordpress 6.0.2 and mysql 5.7 is working fine.

I'm working on an ovh vps with ubuntu 22.04 version.

**Comment by evertramos** [comment]
Hello @nnachtegael,

The error you mentioned on var log basescript I will fix it, it is only a log that basescript tries to save it so you can track your script calls, should be a warning only.

The loop on the db you must check the db container log to see what is wrong, I don't think is something related to this repo, it only gets the components together, maybe some missing configuration in environment variables? 

Please send the container db logs so we can try to help you with that.

**Comment by nnachtegael** [comment]
thanks for the response
so far I will stay on mysql 5.7
the restart loop is probably due to wp 6.0 and mysql 8 compatibilities...
